### ISSUE TITLE
How to run the sonar cnes 

### ISSUE THREAD

**Issue by vishalsvayam** [lequal/sonar-cnes-report#10]
I downloaded the zip file and unzipped it. And when I excute the example command with my project id it is not running. Please help me .

**Comment by vishalsvayam** [comment]
I cannot find sonar-report-cnes.jar in the zip file that I have downloaded please help me with it. It's very urgent I need to generate a report

**Comment by begarco** [comment]
Zip file do not contain any jar but only source code.

You can find the jar file here: https://github.com/lequal/sonar-cnes-report/releases.
