### ISSUE TITLE
CNES Report Plugin Cannot Retrieve Projects on the Generate a Report Page

### ISSUE THREAD

**Issue by aozmez** [lequal/sonar-cnes-report#106]
### Expected behavior
CNES Report Plugin is expected to retrieve project keys on the Generate a Report Page to load the combo box.

### Actual behavior
CNES Report Plugin cannot retrieve project keys on the Generate a Report Page resulting the combo box being empty. In this case when the Generate button is clicked an error message is displayed saying "Please select an item in the list". However, there are no items to select.

To help identifying the issue, I want to share the following "HTTP 404: Not Found" status message from the SonarQube server "access.log" file:
`- [09/Jan/2020:11:07:56 +0000] "GET /api/projects/index HTTP/1.1" 404 56 "http://sonarqube:9000/extension/cnesreport/report"`

### Steps to reproduce behavior

1. Select "CNES Report" item from the top "More" menu in SonarQube Web interface
2. Try selecting a project which is not possible because the combo box is empty
3. Click the "Generate" button which produces a popup displaying "Please select an item in the list."

### Detection version
SonarQube Community Edition: 8.1.0.31237
CNES Report Plugin: 3.1.0

**Comment by aozmez** [comment]
To help understanding the issue better, I want to share the following "HTTP 404: Not Found" status message from the SonarQube server "access.log" file:
`- [09/Jan/2020:11:07:56 +0000] "GET /api/projects/index HTTP/1.1" 404 56 "http://sonarqube:9000/extension/cnesreport/report"`

**Comment by Xvier** [comment]
I created a pull request for this. But the team has not looked into this.

**Comment by Sancretor** [comment]
Hi @aozmez 

Thank you for your feedback !  
Unfortunately, as stated in the project README, we are not compatible with SonarQube 8.x.  
This issue is known but related to an unsupported version, as @Xvier says.  
We don't know when we'll have time to work on this.  
Sorry.

**Comment by aozmez** [comment]
Thanks

**Comment by aozmez** [comment]
I suggest putting this information on the SonarQube Plugin Version Matrix correctly since the current matrix shows CNES Report 3.1.0 as compatible with SonarQube 8.x. That mislead me in the first place.

[https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/](url)

**Comment by Sancretor** [comment]
Hi @aozmez ! 

Thanks for noticing this error, it explains why so many people have this issue with the plugin ...
We'll fix that !

**Comment by Xvier** [comment]
@Sancretor can you check my pull request https://github.com/lequal/sonar-cnes-report/pull/105 its an easy fix but you also have to check your travis-ci pipeline cause its broken on a few parts.

**Comment by Chandra209** [comment]
Any update regarding this? when is the new version going to be released?

**Comment by Sancretor** [comment]
Hi @Chandra209 !

We are currently working on #105 to solve this issue.
The new version will be released when #115 and #112 will be fixed too.
There is no date for the moment.

**Comment by Chandra209** [comment]
@Sancretor Thank you for the update, if there is any quick fix or hack to make it work please do add here.

**Comment by Sancretor** [comment]
@Chandra209 : if this could help you, @DatzAtWork gave a workaround in issue #108
