### ISSUE TITLE
In CNES Report feature, i am not able to get the project key values, so i am not able to get the reports. Please help me out for this issue.

### ISSUE THREAD

**Issue by ankurgupta89-smd** [lequal/sonar-cnes-report#108]

**Comment by Sancretor** [comment]
Hi @ankurgupta89-smd !

Thank you for your feedback !  
Unfortunately, as stated in the project README, we are not compatible with SonarQube 8.x.  
This issue is known but related to an unsupported version.  
We don't know when we'll have time to work on this.  
Sorry.

**Comment by DatzAtWork** [comment]
For me it worked, when I added the project key as select-option in the html page manually.
The generated report looks fine.

**Comment by Chandra209** [comment]
@DatzAtWork What and where did you add exactly in the html page?

**Comment by DatzAtWork** [comment]
@Chandra209 
![grafik](https://user-images.githubusercontent.com/37868477/75685018-31e48400-5c9a-11ea-8ea8-234ddf992d75.png)

**Comment by Alpha004** [comment]
@DatzAtWork i tried but actually get this error:

{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

SonarQube Version: 8.1.0.31237

**Comment by Chandra209** [comment]
@DatzAtWork  same error for me as well...

**Comment by DatzAtWork** [comment]
I think I am using the dev-build. Maybe that's the difference?

**Comment by Sancretor** [comment]
@Chandra209 & @Alpha004 : Did you try to use the standalone version ?
That could be another workaround as it does not rely on the API error.

**Comment by Chandra209** [comment]
@Sancretor, yes I tried with the stand alone version. It is not working.

**Comment by Sancretor** [comment]
@Chandra209 : I just tried on a Docker SonarQube 8.1-community-beta & 8.2-community with Sonar CNES Report 3.1.0 Standalone and it worked, so it should work for you too.  
What is your error with the standalone version ?

**Comment by Chandra209** [comment]
@Sancretor I tried with the normal installation not the docker image

**Comment by Alpha004** [comment]
> @Chandra209 & @Alpha004 : Did you try to use the standalone version ?
> That could be another workaround as it does not rely on the API error.

@Sancretor the problem was the port, I configure sonarqube on port 8080, but cnes take for default port 9000, i change the port and now its working!!. but i change sonarqube 8.2 to 7.9.2 LTS. i dont know if this configuration works in 8.2

**Comment by Sancretor** [comment]
@Alpha004 : Great ! Indeed, 9000 is the default port for SonarQube. The standalone version works on SonarQube 8.2, as I tested yesterday.

@Chandra209 : There may not be much difference between "normal" and "docker" version. At least, based on the CNES Report's code, the standalone version should work on 8.x.
