### ISSUE TITLE
Error generation report Exception in thread "main" org.apache.poi.openxml4j.exceptions.NotOfficeXmlFileException: 

### ISSUE THREAD

**Issue by Moura8** [lequal/sonar-cnes-report#11]
Hi.
Im trying to generate a report from a project.
SonarQube version: 6.4
Server side OS: Ubuntu 16
Client side OS: No client side, a checkout is in the ubuntu server
i have the issues-template.xlsx, code-analysis-template.docx and  sonar-report-cnes.jar in same directory.

# java -jar sonar-report-cnes.jar --sonar.url http://localhost:9000 --sonar.project.id myID--report.template template.docx --report.locale en_US
Jul 04, 2018 4:54:09 PM fr.cnes.sonar.report.input.ParamsFactory create
INFO: Successfully processed parameters.
Exception in thread "main" org.apache.poi.openxml4j.exceptions.NotOfficeXmlFileException: No valid entries or contents found, this is not a valid OOXML (Office Open XML) file
        at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:286)
        at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:756)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:327)
        at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:123)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:165)
 Any idea? Thank you

**Comment by begarco** [comment]
It looks like something went wrong with the file you provided. 

Do you use the Word template provided with the jar file?
Can you correctly open the Word template file with MS Word?
Des the filename in the command line correspond to the one of the file in your directory?

**Comment by Moura8** [comment]
Hi begarco.
Yes the files names matches. i also try to add the issues template path, but no success.

java -jar sonar-report-cnes.jar --sonar.url http://localhost:9000 --sonar.project.id myID --report.template template.docx  --issues.template issues-template.xlsx --report.locale en_US

I cant open the word template in the server because Im operating via SSH .i need to install some version of Word?

**Comment by Moura8** [comment]
Alredy install libreoffice, same output error result :(

**Comment by begarco** [comment]
You don't need to have Office installed but can you open the file with it and tell me if Office warns you of a problem (corrupted file)?

Otherwise can you send me your file?

**Comment by Moura8** [comment]
Indeed the file was corrupted somehow. Issue resolved, thank you so much!
