### ISSUE TITLE
Analysis on all master branches

### ISSUE THREAD

**Issue by naveenkumaran** [lequal/sonar-cnes-report#110]
Is it possible to run the analysis against all the projects(only on master branch)

**Comment by Sancretor** [comment]
Hi @naveenkumaran !

As of now, the plugin does not work with the branch plugin, so generating a report could only be done on master branches.  
You can generate a report on all your projects one by one, there are no feature to generate reports on all projects in a single shot.  
  
Does that answer your question ?

**Comment by naveenkumaran** [comment]
yes

**Comment by naveenkumaran** [comment]
thank you for the reply. the issue can  be closed as feature not available
