### ISSUE TITLE
compatibility with sonarqube 8.1

### ISSUE THREAD

**Issue by userxmen** [lequal/sonar-cnes-report#111]
### Actual behavior
error displayed when generate report :
{"error":"This project can't be exported, please check your token."}

**Comment by Sancretor** [comment]
Hi @userxmen !

Thank you for your feedback !  
This issue is already known, and due to an error inside our marketplace configuration.  
As stated in our README, we are still not compatible with version 8.x of SonarQube.  
We'll be working on this as soon as we have some time ... sorry.
