### ISSUE TITLE
New release 3.2.0 is not available on Sonarqube Marketplace

### ISSUE THREAD

**Issue by DatzAtWork** [lequal/sonar-cnes-report#121]
### Expected behavior
I expected to be able to upgrade to the latest release 3.2.0 in Sonarqube Marketplace

### Actual behavior
Latest release is still 3.1.0
![grafik](https://user-images.githubusercontent.com/37868477/76190556-8d080080-61dd-11ea-93db-b66400bf2be9.png)

### Steps to reproduce behavior
Go to /admin/marketplace?filter=updates and try to update to 3.2.0

**Comment by Sancretor** [comment]
Hi @DatzAtWork !

Indeed, the last release is not yet availaible on the SonarQube Marketplace...  
We'll have to submit a request to the SonarSource team, and wait for their agreement.  
In the meantime, only manual install is available.

**Comment by Sancretor** [comment]
Request to submit the version 3.2.2 on the SonarQube Marketplace is now sent !  
The PR : https://github.com/SonarSource/sonar-update-center-properties/pull/106 
The forum thread : https://community.sonarsource.com/t/new-release-sonarqube-cnes-report-3-2-2/21480
