### ISSUE TITLE
Branch name with slash export cnes report failed.

### ISSUE THREAD

**Issue by 0N0thing** [lequal/sonar-cnes-report#122]
### Expected behavior
Branch name with slash also export report successfully.

### Actual behavior
Can't export, and returned `{"error":"This project can't be exported, please check your token"}`

### Steps to reproduce behavior
1. I configured my sonarqube base url.
2. Export ordinary branch with no slash(for example, project name: **foo**, branch name: **bar**) is succeed
3. When I wanted to export a branch which name with slash is failed also got  `{"error":"This project can't be exported, please check your token"}` .For example, project name: **foo**, branch name: **bar/test**
Nothing showed in web.log at ${SONAR_HOME}/logs/ also cnesreport-0.log in ${SONAR_HOME}/.cnesreport/log/

### Detection version

sonarqube version: 8.2.0 Developer Edition
plugin version: 3.2.0

Thanks for your reply :D

**Comment by Sancretor** [comment]
Hi @0N0thing !

Thanks for your feedback, we appreciate it !  
It should be easy to fix, we'll look into it as soon as possible.

**Comment by 0N0thing** [comment]
> Hi @0N0thing !
> 
> Thanks for your feedback, we appreciate it !
> It should be easy to fix, we'll look into it as soon as possible.

Appreciate! 👍

**Comment by Sancretor** [comment]
As a workaround, you can edit the HTML option element in your web browser, and replace the / by %2F then the report could be generated.

**Comment by 0N0thing** [comment]
> As a workaround, you can edit the HTML option element in your web browser, and replace the / by %2F then the report could be generated.

I will try this method.Of course, if I can export report directly maybe more perfect.Thanks for your suggestion.👏🏼

**Comment by Sancretor** [comment]
Of course, it will be better as a native feature, I agree !  
But in the meantime, it could do the trick if you really need this plugin to work.

**Comment by Sancretor** [comment]
Seems to be a deeper issue after all, as it may also be related to project keys with a slash inside.
