### ISSUE TITLE
Compiled with java 11 src/target, cause problem with java 8 projects.

### ISSUE THREAD

**Issue by james-sorling-wcar** [lequal/sonar-cnes-report#124]
### Expected behavior
Would expect it to work with LTS version 7.9, still allows project to be scanned with java8.

### Actual behavior
The plugin [cnesreport] does not support Java 1.8.0_202: fr/cnes/sonar/plugin/ReportSonarPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 -> [Help 1]

### Steps to reproduce behavior
Run scan of project with java 8.

### Detection version
Used sonarqube 7.9.2 and scanned project with Java8.

**Comment by Sancretor** [comment]
Hi @james-sorling-wcar !

Thanks for your feedback, we really appreciate it !  
Ok, looks like another mistake on our side...  
I'll look into it as soon as possible.

**Comment by Sancretor** [comment]
@james-sorling-wcar  
Could you please build & test the plugin from PR #125 (dev branch) ?  
If it works for you, I will then release a new version.

**Comment by james-sorling-wcar** [comment]
Thanks for the quick response, will test it later tonight.

**Comment by pethers** [comment]
Have tested it now, works well and really appreciate the fast fix.(james-sorling-wcar is my company username :)

**Comment by Sancretor** [comment]
Great !  
Thank you very much for the fast feedback too !  
I have to admit, it's not always that fast... we're mostly doing this during our free time.
