### ISSUE TITLE
Problem generating JAR

### ISSUE THREAD

**Issue by gonhidalgo** [lequal/sonar-cnes-report#130]
I have downloaded the .jar file 
(https://github.com/lequal/sonar-cnes-report/releases/download/3.2.0/sonar-cnes-report-3.2.0.jar)
and added it to the plugin directory, and it works perfectly fine.
However, when i download the sourcode from github
(https://github.com/lequal/sonar-cnes-report) 
and created the .jar file without editing anything from the original code, SonarQube doesnt start.

To convert the source-code to .jar file im using the command: 
 "jar -cf report.jar sonar-cnes-report-3.2.0" being:

-report.jar: name of the .jar file i want to create.
-sonar-cnes-report-3.2.0: the folder which contains the github's source code.

Additionally, Im using SonarQube 7.9.2 (latest LTE) and it requires java-jdk-11.

I guess im not converting correctly from the sourcecode to the .jar file due to the fact im not changing anything from the source code.

Any help with this issue? How is the correct way to convert from the source code to the .jar file?

Best regards.

**Comment by Sancretor** [comment]
Hi @gonhidalgo !

Thanks for you feedback !

You should use version 3.2.2 (not 3.2.0 !) as it contains 2 useful fixes for 3.2.
As you can see in the project's README, it is compatible with SonarQube 7.9 LTS & Java 11.

I suppose you're not familiar with Maven to build Java projects ..? You should look into it !
To build the JAR file you need to use this tool, here is an example command line : `mvn clean package`
It will generate a directory named "target", inside of which you should find the desired JAR file.
Then rename it/move it the way you want...

Does that answer your questions ?

**Comment by gonhidalgo** [comment]
Thanks for your fast reply, it was really helpfull!

Best regards.

**Comment by Sancretor** [comment]
Glad I could help !
