### ISSUE TITLE
Unable to access jarfile sonar-report-cnes.jar

### ISSUE THREAD

**Issue by fastluca** [lequal/sonar-cnes-report#17]
### Expected behavior
Execute the tool
### Actual behavior
Executing the command `java -jar sonar-report-cnes.jar --sonar.token xxx --sonar.url http://54.77.33.180 --sonar.project.id xxx --report.template ./template.docx --report.locale en_EN` I received the error 'Unable to access jarfile'. Tried both on Linux and Windows 10, Java 8.
### Steps to reproduce behavior 
Execute the comand `java -jar sonar-report-cnes.jar --sonar.token xxx --sonar.url http://54.77.33.180 --sonar.project.id xxx --report.template ./template.docx --report.locale en_EN` I received the error 'Unable to access jarfile'
### Detection version
1.2.1

**Comment by begarco** [comment]
It is not a problem: you have downloaded **sonar-cnes-report.jar** but you call **sonar-report-cnes.jar**, use this command instead:
```
java -jar sonar-cnes-report.jar --sonar.token xxx --sonar.url http://54.77.33.180 --sonar.project.id xxx --report.template ./template.docx --report.locale en_EN
```

The readme has been updated.

**Comment by fastluca** [comment]
Thank you so much, it works now!
