### ISSUE TITLE
Support SonarCloud.io

### ISSUE THREAD

**Issue by begarco** [lequal/sonar-cnes-report#25]
### Expected behavior
Enable report projects on SonarCloud.

### Actual behavior
Because of organization feature enabled on SonarCloud, it is not possible to generate reports from SonarCloud.

### Steps to reproduce behavior
Try to call cnesreport with sonarcloud url.

### Detection version
1.2.1

**Comment by begarco** [comment]
There is no way to specify the organization with the new command line.

**Comment by louisjdmartin** [comment]
cnes-report is able to extract report from sonarcloud even if it came from an organization.
