### ISSUE TITLE
cnesreport does NOT work in corporate proxy network and lacks detailed error message

### ISSUE THREAD

**Issue by clemensutschig** [lequal/sonar-cnes-report#40]
### Expected behavior
plugin can connect to sq instance in guarded proxy environment

### Actual behavior
[ERROR] Impossible to reach SonarQube instance.
SonarQube online: false

### Steps to reproduce behavior
try to run cnesreport.jar behind proxy - where sonarqube is also within the same proxy network. 
Tried -D java system properties (non proxy, ... ), and also POSIX ... neither made a difference, and NO usefull error was shown. 

SQ is up and running and can be reached thru browser.

URL format used 
`-s https://sonarqube-cd.<domain>`
 
### Detection version
1.2.1 - latest -> against sq7.3

**Comment by begarco** [comment]
Is there more information in log file (~/.cnesreport/log/cnesreport-0.log)?

We triggered the same issue as yours, for now only SonarQube authentication is supported. Nothing has been done for supporting enterprise proxies.

**Comment by clemensutschig** [comment]
I am trying to come up with an PR for this - including a nice error. 💃

**Comment by begarco** [comment]
@clemensutschig could you provide an usage example of your modificated version. Do you use **-D** option?

**Comment by clemensutschig** [comment]
Yes i do.. just Check the commit. System.getproperty ()
