### ISSUE TITLE
CNES report still contains french vocabs in docx report 

### ISSUE THREAD

**Issue by clemensutschig** [lequal/sonar-cnes-report#44]
### Expected behavior
when language (-l) is provided - all vocabs and label have to switch

### Actual behavior
docx still contains french vocabs

### Steps to reproduce behavior
run cnes reports and check

### Detection version
1.2.1 latest

**Comment by clemensutschig** [comment]
![image](https://user-images.githubusercontent.com/40628552/47707012-f4499400-dc2a-11e8-947c-f2d36e4efcef.png)

![image](https://user-images.githubusercontent.com/40628552/47707044-0f1c0880-dc2b-11e8-81a3-dc7c9dc1f21b.png)

**Comment by karantheangel** [comment]
We find this plugin really helpful !! Thanks for developing this, however, we are facing similar issue where French vocabs still show up in headings/table headers of the docx report.

**Comment by fdvieira** [comment]
I'm experiencing the exact same problem. Any solutions?

**Comment by begarco** [comment]
A solution has been integrated in dev branch and a new release will be released soon on master. Feel free to build from dev branch.

**Comment by fdvieira** [comment]
ok, thanks for the reply.
