### ISSUE TITLE
[BUG] Inconherent severity level between SonarQube Analysis and report 

### ISSUE THREAD

**Issue by labeaua** [lequal/sonar-cnes-report#45]
### Expected behavior
In the word report : 
- Exceptions should not be thrown in finally blocks --> MAJOR
- Empty statement  --> CRITICAL 

### Actual behavior
![bug](https://user-images.githubusercontent.com/44770240/47992547-7afbe680-e0ed-11e8-905d-926f33b48567.png)

In the word report : 
- Exceptions should not be thrown in finally blocks --> CRITICAL
- Empty statement  --> MINOR

### Steps to reproduce behavior
DEBRISK 3.0.a1 code analysis

**Comment by begarco** [comment]
Current behaviour is the following: cnesreport export rules list with usine configuration.

Profile's severity could be used.
