### ISSUE TITLE
Null Pointer Exception in main

### ISSUE THREAD

**Issue by caldarolad** [lequal/sonar-cnes-report#5]
I may be doing this incorrectly, but there is a lack of documentation around how to use this.  I haven't coded anything beyond hello world in java, so I'm not great at reverse engineering this.  Here's the command I'm running 

java -jar sonar-report-cnes.jar --sonar.url MYURLHERE --sonar.project.id 122  --report.template ./template.docx --report.locale en_US

and here's the output

Feb 26, 2018 4:48:08 PM fr.cnes.sonar.report.input.ParamsFactory create
INFO: Successfully processed parameters.
Exception in thread "main" java.lang.NullPointerException
        at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:291)
        at fr.cnes.sonar.report.providers.MeasureProvider.getMeasures(MeasureProvider.java:61)
        at fr.cnes.sonar.report.factory.ReportFactory.create(ReportFactory.java:82)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:138)

**Comment by begarco** [comment]
Could you provide further information about your system?

- SonarQube version:
- Server side OS:
- Client side OS:
- Peculiar configuration of considered project (permissions, etc.):

**Comment by caldarolad** [comment]
SonarQube version: 6.0
Server side OS: Debian 8
Client side OS: Windows 7 Enterprise SP1, but not sure why this is relevant
No peculiar configuration that I'm aware of, we are running sonar from a docker container.

**Comment by begarco** [comment]
Here is a version which is compatible with SonarQube 5.6 to SonarQube 6.0.
Could you tell us if it fix your issue please ?

[sonar-report-cnes.zip](https://github.com/lequal/sonar-cnes-report/files/1816265/sonar-report-cnes.zip)

**Comment by caldarolad** [comment]
that specific error is gone, now I think it's just a matter of not knowing how to use this.

java -jar sonar-report-cnes.jar --sonar.url http://10.152.191.50:443 --sonar.project.id com.flag.enterprise:flag-ent-site --report.locale en_US

Mar 15, 2018 7:59:12 PM fr.cnes.sonar.report.input.ParamsFactory create
INFO: Successfully processed parameters.
Mar 15, 2018 7:59:12 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: [WARN] Impossible to create the following directory: ./conf
Mar 15, 2018 7:59:15 PM fr.cnes.sonar.report.providers.IssuesProvider getIssuesByStatus
WARNING: There are more than 10000 issues to export, but SonarQube is not able to provide all issues. Only the 10000 first issues are reported. Please, reduce the number of issues before retrying to export.
Mar 15, 2018 7:59:19 PM fr.cnes.sonar.report.providers.IssuesProvider getRawIssues
WARNING: There are more than 10000 issues to export, but SonarQube is not able to provide all issues. Only the 10000 first issues are reported. Please, reduce the number of issues before retrying to export.
Mar 15, 2018 7:59:22 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: code-analysis-template.docx (No such file or directory)
java.io.FileNotFoundException: code-analysis-template.docx (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:122)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:165)

Mar 15, 2018 7:59:22 PM fr.cnes.sonar.report.ReportCommandLine main
INFO: Welcome to Sonar Report CNES
Here are the list of parameters you can use:
  > --sonar.url [mandatory]
  > --sonar.project.id [mandatory]
  > --report.author
  > --report.date
  > --report.path
  > --report.conf [yes|no]
  > --report.locale [fr_FR|en_US]
  > --report.template
  > --issues.template
Example :
java -jar sonar-report-cnes.jar --sonar.url http://sonarqube:9000 --sonar.project.id cat



Is code-analysis-template.docx something I am supposed to create?

**Comment by begarco** [comment]
You can use provided templates available here : https://github.com/lequal/sonar-cnes-report/releases

**Comment by caldarolad** [comment]
Great, everything works now, and this report is exactly what I needed. Thanks a million.
