### ISSUE TITLE
Version 2.1.0 Does not work with corporate proxy

### ISSUE THREAD

**Issue by rahulsaini** [lequal/sonar-cnes-report#55]
### Expected behavior
Should work with corporate proxy 

### Actual behavior
Does not work with corporate proxy

### Steps to reproduce the behavior
Jar version: 2.1.0 with BigFix #41 

From corporate proxy issue command:
1) java -Dhttps.proxyHost=proxyServer.com -Dhttps.proxyPort=8080 -jar cnesreport.jar -t sonar_analisys -s http://192.168.214.162:19000 -p ProjectTMSearch -r ./code-analysis-mssearch-template.docx
2) it still results in output
[ERROR] Server answered: <html><head>
....
</head><body id="ERR_CONNECT_FAIL">
<div id="titles">
</div>
<hr>
<div id="content">
<p><h3>URL: <a href="http://192.168.214.162:19000/api/system/status">http://192.168.214.162:19000/api/system/status</h3></a></p>
<br>
<hr>
<br>
<p><b>La connexion 192.168.214.162 a ΘchouΘe</b></p>
<p>Pour signaler cette erreur merci de faire un IT Support.</p>
<br>
<hr>
SonarQube online: false
[ERROR] Impossible to reach SonarQube instance.

### Detection version
2.1.0

**Comment by rahulsaini** [comment]
@begarco @gbonnefille  Is anybody please looking into this?

**Comment by gbonnefille** [comment]
I'm not sure about the problem you encounter.

Reading at the IP of the server (192.168.x.y) I imagine you don't have to use a proxy. It is probably an internal server. Does it work when you do not set the proxyHost and proxyPort?
Remember to set the http.nonProxyHosts if needed.

Furthermore, you set https* properties, while the IP is in HTTP (no 's'). Did you try setting the http.proxyHost and http.proxyPort properties?

Can you elaborate on the expected behaviour?

Reading: https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html

**Comment by rahulsaini** [comment]
I place cnesreport.jar in C:\jars 
from there I check if SonarQube **(SONARQUBE Version is 5.6.3)**  is pingable and it is:
C:\Users\rasaini>ping 192.168.214.162

Pinging 192.168.214.162 with 32 bytes of data:
Reply from 192.168.214.162: bytes=32 time=162ms TTL=56
Reply from 192.168.214.162: bytes=32 time=165ms TTL=56
Reply from 192.168.214.162: bytes=32 time=160ms TTL=56
Reply from 192.168.214.162: bytes=32 time=192ms TTL=56

Ping statistics for 192.168.214.162:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 160ms, Maximum = 192ms, Average = 169ms

Then I issue command line 
**java -Dhttp.proxyHost=proxy38-master.one.steria.dom -Dhttp.proxyPort=8080 -jar cnesreport.jar -t sonar_analisys -s http://192.168.214.162:19000 -p ms-etmdn-tmdsview-search -r ./code-analysis-mssearch-template.docx**

I get a response:
**See attached SonarCNESError.txt**

[SonarCNESError.txt](https://github.com/lequal/sonar-cnes-report/files/3042471/SonarCNESError.txt)

**Comment by rahulsaini** [comment]
@begarco @gbonnefille Please see my latest response as it is not working even after your suggestions.

**Comment by gbonnefille** [comment]
As spotted on my previous comment, are you sure you need to go through the proxy?
Did you try without setting the proxy properties?

Looking at your error, it seems that the proxy is not able to contact the sonar server.

**Comment by begarco** [comment]
I agree with @gbonnefille, using proxy in your case seems useless: could you try running the following command and send us back the result:
```
java -jar cnesreport.jar -t sonar_analisys -s http://192.168.214.162:19000 -p ms-etmdn-tmdsview-search -r ./code-analysis-mssearch-template.docx
```

**Comment by rahulsaini** [comment]
c:\Jars>java -jar cnesreport.jar -t sonar_analisys -s http://192.168.214.162:19000 -p ms-etmdn-tmdsview-search -r ./code-analysis-mssearch-template.docx
SonarQube URL: http://192.168.214.162:19000
[ERROR] Unauthorized error sent by SonarQube server (code 401), please provide a valid authentication token to cnesreport.
SonarQube online: false
[ERROR] Impossible to reach SonarQube instance.

![ScreenShot 092](https://user-images.githubusercontent.com/1378753/55604578-21781080-578e-11e9-8cad-694d5a61f866.JPG)

**Comment by rahulsaini** [comment]
Do I need to set up some kind of token for **cnesreport** ?

**Comment by begarco** [comment]
Yes, you need to go on Sonarqube web interface, then in your profile and then in security tab to generate a token.

Use this token with -t option of cnesreport.

Your error is not a proxy authentication error but a Sonarqube authentication error.

**Comment by rahulsaini** [comment]
Worked. Worked with the Token ID and NOT the token name. 
**java -jar cnesreport.jar -t edf914b55cc6ca3a7c42d705926564f4b99a5792 -s http://192.168.214.162:19000 -p ms-etmdn-tmdsview-search -r ./code-analysis-mssearch-template.docx**
Thanks a lot for helping on this. The reports are comprehensive enough. I loved the Pivoted report in the generated Excel!!
 
![ScreenShot 093](https://user-images.githubusercontent.com/1378753/55607461-e1b72600-5799-11e9-9cd6-3329aac6792b.JPG)

Thanks again for one comprehensive Sonar report producing software. The Excel export makes it way easy to filter and track all the issues to be addressed.

**Comment by rahulsaini** [comment]
Closing the issue with a token of my thanks again and keep up the good work !!!
