### ISSUE TITLE
Report Security

### ISSUE THREAD

**Issue by philippeaquino** [lequal/sonar-cnes-report#56]
Hello , i want to give you a prestigious project: 

I'm using in my work environment because I'm from the infrastructure area, and very good, very much so.

I Wanted to ask you if and possible general the OWASP reports Top 10 and SANS TOP 25 in docx?

**Comment by Sancretor** [comment]
Hi @philippeaquino ! 

Thank you for your feedback, but we don't understand what you'd like us to do.

Would you like a new feature in Sonar CNES Report to retrieve metrics from the Sonar OWASP Dependency Check Plugin ?

**Comment by philippeaquino** [comment]
Hello thanks for the reply,

I would like the docx report to contain the Sonarquebe security reports.

OWASP Top 10 and SANS Top 25, along with the HostSpot Security.

For example, see this Link:

http://sonarurl:8080/api/issues/search?types=SECURITY_HOTSPOT&facets=projects

Follow the images below

![Screenshot_1](https://user-images.githubusercontent.com/11314302/57930532-1a284480-78ae-11e9-8bcb-cf508a52fdb7.png)
![Screenshot_2](https://user-images.githubusercontent.com/11314302/57930533-1ac0db00-78ae-11e9-8e2e-85d16be3e0a9.png)

**Comment by Sancretor** [comment]
Hi @philippeaquino !  
  
Thanks for your explanation, we all agree it would be useful !  
This feature was introduced with SonarQube 7.3, but our policy is to be compatible with LTS versions of SonarQube, so we don't have to update the project at every release.  
As the next LTS (7.9) will be released soon, we will upgrade the Sonar CNES Report, and add a Security Report feature in it !

**Comment by Sancretor** [comment]
See #66 to follow this topic
