### ISSUE TITLE
Release is not a plugin for SonarQube 6.7.1

### ISSUE THREAD

**Issue by jackperalta** [lequal/sonar-cnes-report#6]
Hi,

I downloaded the release v1.1.0 and tried to load it in SonarQube 6.7.1, which fails with the message

> 2018.03.16 09:04:17 ERROR web[][o.s.s.p.Platform] Web server startup failed: File is not a plugin. Please delete it and restart: C:\dev\sonarqube-6.7.1\extensions\plugins\sonar-cnes-report-1.0.jar

I also tried it by cloning the repo and build it with maven, but with the same result.

**Comment by begarco** [comment]
This is a standalone software you can use as follow:
`java -jar sonar-report-cnes.jar --sonar.url http://sonarqube:9000 --sonar.project.id my-project-id --report.template ./template.docx --report.locale fr_FR`

This is not a plugin for SonarQube: our goal is to be able to retrieve reports from anywhere (another server like Jenkins for example), you just need SonarQube's url.

**Comment by jackperalta** [comment]
ah good to know - thanks
