### ISSUE TITLE
branches support

### ISSUE THREAD

**Issue by vitas** [lequal/sonar-cnes-report#63]
### Expected behavior
have report for different scm branches (for developer sonarqube license)
### Actual behavior
report only for master branch

**Comment by Sancretor** [comment]
Hi @vitas !  
Thanks for your feedback, we appreciate it !  
Unfortunately, the branch feature is part of SonarQube Developer Edition, which is not free of charge.  
Our team cannot afford it, so we can't work on this feature in the present situation.  

If you have a licence, and want to contribute to this project, feel free to send us your Pull Request !  
This feature would be very useful.
