### ISSUE TITLE
Upgrade Sonar CNES Report Compatibility with SonarQube 7.9 LTS

### ISSUE THREAD

**Issue by Sancretor** [lequal/sonar-cnes-report#65]
### Expected behavior
Sonar CNES Report should be compatible with the last LTS version of SonarQube.

### Actual behavior
It is not.

### Steps to reproduce behavior
Try to use the tool on a SonarQube 7.9 server.

### Detection version
2.1.0

**Comment by Srivishnujammula** [comment]
Hello, its a good effort to initiate it. appreciate you guys, Is there any  jar for sonarqube 7.3 ?

**Comment by Sancretor** [comment]
Hi @Srivishnujammula !  
  
Thank you for the support, it's highly appreciated !  
You can try to use the latest version of our tool (2.2.0) on SonarQube 7.3, but without any guaranty.  
Let us know if your test is successful !  
  
Otherwise, we don't have anything yet for this specific version of SonarQube.
