### ISSUE TITLE
Summary report

### ISSUE THREAD

**Issue by vasinle** [lequal/sonar-cnes-report#67]
### Expected behavior
cnesreport
### Detection version

Can I export report.
    Only Summary(Don't need detail.)
         Have template only summary information?
          or have technique to export only summary information?

**Comment by vasinle** [comment]
![image](https://user-images.githubusercontent.com/42170749/58859349-c0a87e00-86d3-11e9-9565-c2046cb4d09a.png)

**Comment by Sancretor** [comment]
Hi @vasinle !
Thank you for your feedback, we appreciate it !
  
If you don't want the report to include those details, you just have to give it a new template !  
To do so, create a new template or modify the default one, and use the command line option (`-r`) to specify the path to it. Here is an example in the README : https://github.com/lequal/sonar-cnes-report#advanced-usage  
You can download our default template on our Github release page.  
  
Does that answer your question ?

**Comment by Sancretor** [comment]
Without any answer for a month on this question, we consider the subject as closed.
