### ISSUE TITLE
Unable to generate sonar CNES report throws {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

### ISSUE THREAD

**Issue by Ashifmd** [lequal/sonar-cnes-report#98]
### Expected behavior
It should generate a report file
### Actual behavior
when i click on more> CNES report> generate it throws below error
{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
### Steps to reproduce behavior
Tried different version but no use
### Detection version
My current sonarqube version:6.7.6
CNES report plugin: 3.1.0
sonar i -code cnes plugin: 1.1.0

Can someone help me to get rid of this error?
![image](https://user-images.githubusercontent.com/57474671/68362372-1387d500-014d-11ea-8ea1-e9c3d832d648.png)

error:
![image](https://user-images.githubusercontent.com/57474671/68362392-1edb0080-014d-11ea-961d-f78df03af421.png)

**Comment by begarco** [comment]
Thanks for using the cnesreport.

Could you provide us more information?
+ If you use it as standalone, share us the content of the directory `.cnesreport` which should be created in your home directory at first launch.
+ If you use it as SonarQube plugin, share us the content of the file `web.log` which should be in `${SONAR_HOME}/log/`.

**Remind to anonymize your personnal data before posting them.**

Regards.

**Comment by Ashifmd** [comment]
Hello @begarco 

Thanks for your response 
I found the solution with logs from sonar server

**error logs**:  **http:**//xxx.xxxx.xxxxxxx/sonarqube/api/cnesreport/report?key=sleroy%3Asample-project&author=usertoken=d417sdsdffgdghh6656765uhhf4eac5dfd64d4&generation=Generate 

**issue:**
the above URL should be HTTPS not HTTP , so i set the "**server base URL**" configuration in sonar under below location 

**Solution:**
Administration>Configuration>Server base URL: https://xxxxx.xyyyyy.com
now URL redirects to correct path and it generates the report

Cheers!!

**Comment by hepter** [comment]
I'm still getting this error. I guess it occurs because I use ip:port instead of domain

**Comment by OoiYeeJing** [comment]
I added mine like this http://xxx.yyy.com:9000/sonar/ works.

**Comment by vincentskooi** [comment]
I added mine like this in Server base URL and it worked: http://xxx.yyyy.com:9000/sonar/
