### ISSUE TITLE
CNES-Report doesn't list project keys for projects scanned before installation

### ISSUE THREAD

**Issue by smclinden** [lequal/sonar-cnes-report#99]
### Expected behavior

More>CNES Report>Project Key listbox is empty

### Actual behavior

There are three projects already scanned, with keys. I would expect that these would be available in the listbox.

### Steps to reproduce behavior

Install CNES Report after scanning projects.

### Detection version

3.1.0 Sonarqube 8.0

**Comment by jtbatzer** [comment]
I can confirm this behavior.

**Detection version
**
3.1.0 Sonarqube 8.0

Partial log from server
[access.log](https://github.com/lequal/sonar-cnes-report/files/3826712/access.log)

**Comment by Sancretor** [comment]
Hi @smclinden and @jtbatzer !

Thanks for your feedback !  
Unfortunately, I see that both of you are working on SonarQube 8.0 whereas we don't show any compatibility with it.
As you could see in the project's README.md, it works on SonarQube 7.9 LTS but not above.
  
We will look into it later, when working on 8.x compatibility.

**Comment by smclinden** [comment]
Ah, that would explain it.

**Comment by so87** [comment]
Is there anything plan to fix this for 8.x?

**Comment by jakedent** [comment]
There's still a way to generate the reports, bit of a hack rather than a solution. 

In the browser, right-click the list box and click inspect element. Remove the select tag and paste:

`<input type="text" id="key" name="key" class="login-input">`

I managed to type in my projectKey and generate reports. 

Am using SonarQube 8.2.0.32929.

**Comment by Sancretor** [comment]
Hi @jakedent !

Are you using version 3.2.2 of the plugin ?
If you mean that the problem still exists in the last release, I will reopen this issue.

**Comment by jakedent** [comment]
Apologies, ended up with 3.1.

**Comment by jtbatzer** [comment]
I can confirm the problem is resolved.  I recently upgraded to SonarQube 8.2 and upgraded all plugins and was able to generate the report.
